# Generated by Django 4.2.4 on 2023-10-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreArticulo', models.CharField(default='', max_length=40)),
                ('NombreProveedor', models.CharField(default='', max_length=40)),
                ('CodigoArticulo', models.CharField(default='', max_length=30)),
                ('TotalPedidoCLP', models.IntegerField()),
                ('CostoEnvioCLP', models.IntegerField()),
                ('AduanaCLP', models.IntegerField()),
                ('IVAclp', models.IntegerField()),
                ('AduanaMasIVACLP', models.IntegerField()),
                ('CostoTotalCLP', models.IntegerField()),
                ('CostoTotalUSD', models.IntegerField()),
            ],
        ),
    ]
